#!/usr/bin/env python3
"""Generate deterministic NumPy reference values for native runtime parity."""

from __future__ import annotations

import argparse
import pathlib

import numpy as np


def layer_norm(values: np.ndarray) -> np.ndarray:
    mean = values.mean(axis=-1, keepdims=True)
    variance = ((values - mean) ** 2).mean(axis=-1, keepdims=True)
    return (values - mean) / np.sqrt(variance + 1e-5)


def attention(query: np.ndarray, key: np.ndarray, value: np.ndarray) -> np.ndarray:
    scores = query @ key.T / np.sqrt(query.shape[-1])
    scores -= scores.max(axis=-1, keepdims=True)
    weights = np.exp(scores)
    weights /= weights.sum(axis=-1, keepdims=True)
    return weights @ value


def reference_rows() -> dict[str, np.ndarray]:
    query = np.array([[1.0, 0.0], [0.0, 1.0]], dtype=np.float64)
    key = query.copy()
    value = np.array([[10.0, 20.0], [30.0, 40.0]], dtype=np.float64)
    attention_expected = attention(query, key, value)

    timestep = 1.5
    frequencies = np.exp(-np.log(10000.0) * np.arange(2, dtype=np.float64) / 2.0)
    angles = timestep * frequencies
    timestep_expected = np.concatenate((np.sin(angles), np.cos(angles)))

    final_hidden = np.array([[0.0, 0.0], [1.0, -1.0]], dtype=np.float64)
    final_expected = layer_norm(final_hidden)[1]

    block_input = query.copy()
    normalized = layer_norm(block_input)
    hidden = block_input + attention(normalized, normalized, normalized)
    cross_value = np.array([3.0, 1.0], dtype=np.float64)
    conditioned_expected = hidden + cross_value

    return {
        "q": query.reshape(-1),
        "k": key.reshape(-1),
        "v": value.reshape(-1),
        "attention_expected": attention_expected.reshape(-1),
        "timestep_expected": timestep_expected,
        "final_expected": final_expected,
        "conditioned_expected": conditioned_expected.reshape(-1),
    }


def render() -> str:
    lines = ["# Generated by tests/generate_native_reference.py using NumPy float64."]
    for name, values in reference_rows().items():
        encoded = ",".join(f"{value:.12g}" for value in values)
        lines.append(f"{name},{encoded}")
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("fixture", type=pathlib.Path)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = render()
    if args.check:
        actual = args.fixture.read_text(encoding="utf-8")
        if actual != expected:
            raise SystemExit(f"native reference fixture is stale: {args.fixture}")
    else:
        args.fixture.write_text(expected, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
